version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: jean
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: db
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"